name: auto_matical_study_correct
description: Contract-driven Flutter and mini program clients for automatic homework grading.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.7.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  logger: ^2.0.2
  web_socket_channel: ^3.0.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0
  collection: ^1.18.0
  image: ^4.2.0
  crypto: ^3.0.3
  path: ^1.9.0
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  package_info_plus: ^8.0.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
